# Build environment for better-chess-engine.
#
# This image only carries the toolchain (meson, ninja, clang-19, spdlog,
# gtest, oneTBB). It does not bundle the source: mount the repo at
# /workspace and build inside the container, so the host never needs any
# of these dependencies installed.
#
#   docker build -t bce-builder .
#   docker run --rm -it --user "$(id -u):$(id -g)" -v "$PWD":/workspace bce-builder
#   (inside the container) meson setup build -Dmode=release -Dconsole=true
#                           ninja -C build
#                           ./build/src/main/chess
#
# Or non-interactively:
#   docker run --rm --user "$(id -u):$(id -g)" -v "$PWD":/workspace bce-builder \
#       bash -c "meson setup build -Dmode=test && ninja -C build && ./build/tests/test_engine"
#
# --user matches your host UID/GID, so files written into build/ (a bind
# mount) stay owned by you instead of root (the container runs as root by
# default).

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Same package list as .github/workflows/build.yml, so local builds match CI.
# locales is extra: not needed to build, but the --bench output formats
# numbers with std::locale{"en_US.UTF-8"}, which a minimal Ubuntu image
# doesn't have generated by default.
RUN apt-get update && apt-get install -y --no-install-recommends \
        meson \
        ninja-build \
        clang-19 \
        lld-19 \
        g++-14 \
        build-essential \
        libspdlog-dev \
        libgtest-dev \
        libtbb-dev \
        pkg-config \
        ca-certificates \
        locales \
    && locale-gen en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

ENV CC=clang-19
ENV CXX=clang++-19
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

WORKDIR /workspace

CMD ["bash"]
